using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text.Json;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using FactoryCutPlanner.Data;
using FactoryCutPlanner.Models;
using Microsoft.EntityFrameworkCore;

namespace FactoryCutPlanner.ViewModels;

/// <summary>
/// ViewModel for the Products page (Ürün Tanımları).
///
/// Mirrors the Python ProductsFrame functionality:
///   - Left panel: form to add new products with specs + BOM
///   - Right panel: DataGrid listing all products
///
/// Uses CommunityToolkit.Mvvm source generators:
///   [ObservableProperty] → generates INotifyPropertyChanged boilerplate
///   [RelayCommand]       → generates ICommand implementations for button bindings
/// </summary>
public partial class ProductsPageViewModel : ViewModelBase
{
    // ── Product list (right panel) ──
    public ObservableCollection<ProductListItem> Products { get; } = new();

    // ── Form fields (left panel) ──
    [ObservableProperty]
    private string _productName = string.Empty;

    [ObservableProperty]
    private string _description = string.Empty;

    // Product type dropdown — matches Python's _TYPE_LABELS
    public string[] ProductTypeOptions { get; } =
    [
        "Dikdörtgen Kanal",
        "Klima Santrali (AHU)",
        "Bağlantı Parçası (Fitting)",
    ];

    [ObservableProperty]
    private string _selectedProductType = "Dikdörtgen Kanal";

    // Spec fields — all stored as strings for form binding, parsed to decimal on save
    // These map to the JSON "attributes" column per product type.

    // Rectangular Duct specs
    [ObservableProperty] private string _specWidth = string.Empty;
    [ObservableProperty] private string _specHeight = string.Empty;
    [ObservableProperty] private string _specLength = string.Empty;
    [ObservableProperty] private string _specThickness = string.Empty;
    [ObservableProperty] private bool _specInsulationEnabled;

    // AHU specs (reuse width/height/length, add panel thickness & profile)
    [ObservableProperty] private string _specPanelThickness = string.Empty;
    [ObservableProperty] private bool _specHasProfileFramework = true;

    // Fitting specs
    public string[] FittingShapeOptions { get; } =
        ["Dirsek", "Te", "Redüksiyon", "Ofset", "Geçiş"];

    [ObservableProperty]
    private string _selectedFittingShape = "Dirsek";

    [ObservableProperty] private string _specMainDimension = string.Empty;
    [ObservableProperty] private string _specFittingThickness = string.Empty;
    [ObservableProperty] private string _specAngle = string.Empty;

    // ── BOM rows (dynamic add/remove) ──
    public ObservableCollection<BomItemViewModel> BomItems { get; } = new();

    // ── Status / error messages ──
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasStatus))]
    private string _statusMessage = string.Empty;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(StatusColor))]
    private bool _isError;

    public bool HasStatus => !string.IsNullOrEmpty(StatusMessage);
    public string StatusColor => IsError ? "#F38BA8" : "#A6E3A1";

    // ── Computed visibility for spec panels ──
    // The view binds IsVisible to these. When product type changes,
    // partial method OnSelectedProductTypeChanged fires automatically.
    [ObservableProperty]
    private bool _isRectangularDuct = true;

    [ObservableProperty]
    private bool _isAhuCabinet;

    [ObservableProperty]
    private bool _isFittingDuct;

    public ProductsPageViewModel()
    {
        LoadProducts();
    }

    /// <summary>
    /// Auto-generated by CommunityToolkit when SelectedProductType changes.
    /// Toggles which spec panel is visible.
    /// </summary>
    partial void OnSelectedProductTypeChanged(string value)
    {
        IsRectangularDuct = value == "Dikdörtgen Kanal";
        IsAhuCabinet = value == "Klima Santrali (AHU)";
        IsFittingDuct = value == "Bağlantı Parçası (Fitting)";
    }

    // ================================================================
    //  COMMANDS
    // ================================================================

    [RelayCommand]
    private void AddBomRow()
    {
        BomItems.Add(new BomItemViewModel());
    }

    [RelayCommand]
    private void RemoveBomRow(BomItemViewModel item)
    {
        BomItems.Remove(item);
    }

    [RelayCommand]
    private void SaveProduct()
    {
        // Validate required fields
        if (string.IsNullOrWhiteSpace(ProductName))
        {
            ShowStatus("Ürün adı zorunludur.", true);
            return;
        }

        try
        {
            // Build the attributes dictionary based on product type
            var productType = GetProductTypeCode(SelectedProductType);
            var attributes = BuildAttributes(productType);

            using var db = new AppDbContext();

            var now = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");

            var product = new Product
            {
                Name = ProductName.Trim(),
                Description = string.IsNullOrWhiteSpace(Description) ? null : Description.Trim(),
                ProductType = productType,
                Attributes = attributes,
                CreatedAt = now,
                UpdatedAt = now,
            };

            db.Products.Add(product);
            db.SaveChanges();

            // Save BOM items
            foreach (var bomVm in BomItems)
            {
                if (string.IsNullOrWhiteSpace(bomVm.MaterialName))
                    continue;

                var bomItem = new BomItem
                {
                    ProductId = product.Id,
                    Name = bomVm.MaterialName.Trim(),
                    Unit = string.IsNullOrWhiteSpace(bomVm.Unit) ? null : bomVm.Unit.Trim(),
                    QuantityPerUnit = ParseDecimal(bomVm.QuantityPerUnit, 1m),
                    CostPerUnit = string.IsNullOrWhiteSpace(bomVm.CostPerUnit)
                        ? null
                        : ParseDecimalNullable(bomVm.CostPerUnit),
                    CreatedAt = now,
                    UpdatedAt = now,
                };

                db.BomItems.Add(bomItem);
            }

            db.SaveChanges();

            ClearForm();
            LoadProducts();
            ShowStatus($"'{product.Name}' ürünü kaydedildi.", false);
        }
        catch (Exception ex)
        {
            ShowStatus($"Hata: {ex.Message}", true);
        }
    }

    [RelayCommand]
    private void DeleteProduct(ProductListItem item)
    {
        if (item == null) return;

        try
        {
            using var db = new AppDbContext();
            var product = db.Products
                .Include(p => p.BomItems)
                .FirstOrDefault(p => p.Id == item.Id);

            if (product == null)
            {
                ShowStatus("Ürün bulunamadı.", true);
                return;
            }

            // Check if product is used in any work order line
            var isUsed = db.WorkOrderLines.Any(wol => wol.ProductId == item.Id);
            if (isUsed)
            {
                ShowStatus("Bu ürün bir iş emrinde kullanılıyor, silinemez.", true);
                return;
            }

            db.BomItems.RemoveRange(product.BomItems);
            db.Products.Remove(product);
            db.SaveChanges();

            LoadProducts();
            ShowStatus($"'{item.Name}' silindi.", false);
        }
        catch (Exception ex)
        {
            ShowStatus($"Silme hatası: {ex.Message}", true);
        }
    }

    // ================================================================
    //  DATA LOADING
    // ================================================================

    private void LoadProducts()
    {
        Products.Clear();

        try
        {
            using var db = new AppDbContext();
            var products = db.Products
                .Include(p => p.BomItems)
                .OrderByDescending(p => p.Id)
                .ToList();

            foreach (var p in products)
            {
                Products.Add(new ProductListItem
                {
                    Id = p.Id,
                    Name = p.Name,
                    Description = p.Description ?? string.Empty,
                    ProductType = p.ProductType,
                    ProductTypeLabel = GetProductTypeLabel(p.ProductType),
                    SpecSummary = FormatSpecSummary(p.ProductType, p.Attributes),
                    BomCount = p.BomItems.Count,
                    BomSummary = FormatBomSummary(p.BomItems),
                });
            }
        }
        catch (Exception ex)
        {
            ShowStatus($"Ürünler yüklenemedi: {ex.Message}", true);
        }
    }

    // ================================================================
    //  FORM HELPERS
    // ================================================================

    private void ClearForm()
    {
        ProductName = string.Empty;
        Description = string.Empty;
        SelectedProductType = "Dikdörtgen Kanal";

        SpecWidth = string.Empty;
        SpecHeight = string.Empty;
        SpecLength = string.Empty;
        SpecThickness = string.Empty;
        SpecInsulationEnabled = false;

        SpecPanelThickness = string.Empty;
        SpecHasProfileFramework = true;

        SelectedFittingShape = "Dirsek";
        SpecMainDimension = string.Empty;
        SpecFittingThickness = string.Empty;
        SpecAngle = string.Empty;

        BomItems.Clear();
    }

    private void ShowStatus(string message, bool isError)
    {
        StatusMessage = message;
        IsError = isError;
    }

    // ================================================================
    //  ATTRIBUTE BUILDERS (product type → JSON dictionary)
    // ================================================================

    private Dictionary<string, JsonElement> BuildAttributes(string productType)
    {
        // Build a temporary object, serialize to JSON, then deserialize to Dictionary.
        // This matches how the Python side stores attributes.
        object specObj = productType switch
        {
            "RECTANGULAR_DUCT" => new
            {
                width_mm = ParseDecimal(SpecWidth, 0m),
                height_mm = ParseDecimal(SpecHeight, 0m),
                length_mm = ParseDecimal(SpecLength, 0m),
                thickness_mm = ParseDecimal(SpecThickness, 0m),
                insulation_enabled = SpecInsulationEnabled,
            },
            "AHU_CABINET" => new
            {
                width_mm = ParseDecimal(SpecWidth, 0m),
                height_mm = ParseDecimal(SpecHeight, 0m),
                length_mm = ParseDecimal(SpecLength, 0m),
                panel_thickness_mm = ParseDecimal(SpecPanelThickness, 0m),
                has_profile_framework = SpecHasProfileFramework,
            },
            "FITTING_DUCT" => new
            {
                fitting_shape = GetFittingShapeCode(SelectedFittingShape),
                main_dimension_mm = ParseDecimal(SpecMainDimension, 0m),
                thickness_mm = ParseDecimal(SpecFittingThickness, 0m),
                angle_degrees = ParseDecimalNullable(SpecAngle),
            },
            _ => throw new InvalidOperationException($"Unknown product type: {productType}")
        };

        var json = JsonSerializer.Serialize(specObj);
        return JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(json)!;
    }

    // ================================================================
    //  MAPPING HELPERS
    // ================================================================

    private static string GetProductTypeCode(string label) => label switch
    {
        "Dikdörtgen Kanal" => "RECTANGULAR_DUCT",
        "Klima Santrali (AHU)" => "AHU_CABINET",
        "Bağlantı Parçası (Fitting)" => "FITTING_DUCT",
        _ => "RECTANGULAR_DUCT",
    };

    private static string GetProductTypeLabel(string code) => code switch
    {
        "RECTANGULAR_DUCT" => "Dikdörtgen Kanal",
        "AHU_CABINET" => "Klima Santrali (AHU)",
        "FITTING_DUCT" => "Bağlantı Parçası (Fitting)",
        _ => code,
    };

    private static string GetFittingShapeCode(string label) => label switch
    {
        "Dirsek" => "ELBOW",
        "Te" => "TEE",
        "Redüksiyon" => "REDUCER",
        "Ofset" => "OFFSET",
        "Geçiş" => "TRANSITION",
        _ => label,
    };

    private static string GetFittingShapeLabel(string code) => code switch
    {
        "ELBOW" => "Dirsek",
        "TEE" => "Te",
        "REDUCER" => "Redüksiyon",
        "OFFSET" => "Ofset",
        "TRANSITION" => "Geçiş",
        _ => code,
    };

    // ================================================================
    //  FORMATTING HELPERS
    // ================================================================

    /// <summary>
    /// Produces a human-readable summary of spec attributes.
    /// Mirrors Python's _format_spec_summary.
    /// </summary>
    private static string FormatSpecSummary(string productType, Dictionary<string, JsonElement> attrs)
    {
        try
        {
            return productType switch
            {
                "RECTANGULAR_DUCT" =>
                    $"{GetAttr(attrs, "width_mm")} × {GetAttr(attrs, "height_mm")} × {GetAttr(attrs, "length_mm")} mm  •  Sac: {GetAttr(attrs, "thickness_mm")} mm"
                    + (GetAttrBool(attrs, "insulation_enabled") ? "  •  Yalıtımlı" : ""),

                "AHU_CABINET" =>
                    $"{GetAttr(attrs, "width_mm")} × {GetAttr(attrs, "height_mm")} × {GetAttr(attrs, "length_mm")} mm  •  Panel: {GetAttr(attrs, "panel_thickness_mm")} mm"
                    + (GetAttrBool(attrs, "has_profile_framework") ? "  •  Profil Çerçeve: Evet" : ""),

                "FITTING_DUCT" =>
                    $"Şekil: {GetFittingShapeLabel(GetAttrStr(attrs, "fitting_shape"))}  •  Ölçü: {GetAttr(attrs, "main_dimension_mm")} mm  •  Sac: {GetAttr(attrs, "thickness_mm")} mm",

                _ => "-",
            };
        }
        catch
        {
            return "-";
        }
    }

    private static string FormatBomSummary(ICollection<BomItem> bomItems)
    {
        if (bomItems.Count == 0) return string.Empty;

        var names = bomItems.Take(3).Select(b => b.Name);
        var suffix = bomItems.Count > 3 ? $" +{bomItems.Count - 3}" : "";
        return $"BOM ({bomItems.Count}): {string.Join(", ", names)}{suffix}";
    }

    // ── JSON attribute access helpers ──

    private static string GetAttr(Dictionary<string, JsonElement> attrs, string key)
    {
        if (attrs.TryGetValue(key, out var el))
        {
            if (el.ValueKind == JsonValueKind.Number) return el.GetDecimal().ToString("G");
            return el.ToString() ?? "?";
        }
        return "?";
    }

    private static string GetAttrStr(Dictionary<string, JsonElement> attrs, string key)
    {
        if (attrs.TryGetValue(key, out var el)) return el.GetString() ?? "";
        return "";
    }

    private static bool GetAttrBool(Dictionary<string, JsonElement> attrs, string key)
    {
        if (attrs.TryGetValue(key, out var el) && el.ValueKind == JsonValueKind.True) return true;
        return false;
    }

    // ── Parsing helpers ──

    private static decimal ParseDecimal(string value, decimal fallback)
    {
        if (string.IsNullOrWhiteSpace(value)) return fallback;
        // Support both comma and dot as decimal separator
        value = value.Replace(',', '.');
        return decimal.TryParse(value, System.Globalization.NumberStyles.Any,
            System.Globalization.CultureInfo.InvariantCulture, out var result) ? result : fallback;
    }

    private static decimal? ParseDecimalNullable(string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        value = value.Replace(',', '.');
        return decimal.TryParse(value, System.Globalization.NumberStyles.Any,
            System.Globalization.CultureInfo.InvariantCulture, out var result) ? result : null;
    }
}

/// <summary>
/// Presentation model for a product row in the DataGrid / list.
/// Separates display concerns from the EF Core entity.
/// </summary>
public class ProductListItem
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string ProductType { get; set; } = string.Empty;
    public string ProductTypeLabel { get; set; } = string.Empty;
    public string SpecSummary { get; set; } = string.Empty;
    public int BomCount { get; set; }
    public string BomSummary { get; set; } = string.Empty;
}
